# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Emacs - ${{ matrix.emacs }}
    strategy: 
      matrix:
        emacs:
        - emacs-24.4-travis
        - emacs-24.5-travis
        - emacs-25.1-travis
        - emacs-25.2-travis
        - emacs-25.3-travis
        - emacs-26.1-travis-linux-xenial
        - emacs-26.2-travis-linux-xenial
        - emacs-26.3-travis-linux-xenial
        - emacs-27.1-travis-linux-xenial
        - emacs-git-snapshot-travis-linux-xenial

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install EVM
        run: |
          git clone https://github.com/rejeep/evm.git ~/.evm
          export PATH="$HOME/.evm/bin:$PATH"
          evm config path /tmp

      - name: Install Emacs ${{ matrix.emacs }}
        run: |
          export PATH="$HOME/.evm/bin:$PATH"
          evm install ${{ matrix.emacs }} --use --skip

      - name: Test cask
        run: cask

      - name: Run a multi-line script
        run: |
          emacs --version
          make test
